import "./Styles/globals.css";
import { Rubik } from "next/font/google";
import Providers from "./providers";
import Navbar from "@components/Navbar";
import Footer from "./Components/Footer";
const rubik = Rubik({
  preload:true,
 subsets: ["latin"],
 weight: "400",
 style: ["normal"],
 display: "swap",
 variable:"--rubik",
});

const metadata = {
 title: "Tienda Gaming STARTX",
 description: "Generated by create next app",
 
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
 return (
  <html lang="es" className={`${rubik.variable}`} >
   <body>
     <Navbar />
     {children}
    <Footer/>
   </body>
  </html>
 );
}

export { metadata };
